### ISSUE TITLE
HP count should be affected by more than just defense skill

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#129] opened 2018-01-22 03:01 UTC
This is a change I'd like to see rolled back or heavily modified. I can see the thinking behind why HP was directly linked to defense hones at one point, but I don't feel it's the right move. This game is not about who tanks the most, as most classes don't tank.

I think we need traditional D&D style leveling where you gain a dice worth of HP upon gaining a level. 

A more complex solution: Perhaps the Defense skill could grant some percentage of the HP total. Maybe 25% of a characters total HP comes from Defense hones. Certainly not all of it. It makes more sense this way to me.

**Comment by rmsr** [comment] 2018-01-22 07:24
An alternative, that links in with our discussion on a gear-wearing skill, is to have defense hone under more circumstances than just tanking. No circumstances come immediately to mind though.

**Comment by rmsr** [comment] 2018-01-22 07:27
Or this is wontfix because the obvious solution is to just spend more time tanking. Tempted to call it that.

Doesn't help that the help file for the defense skill is so wildly inaccurate I am frankly baffled.

**Comment by drewhershey** [comment] 2018-01-23 04:39
Sorry, this is gonna be pretty long.

It never really made sense to me either that a character's max HP was based
much more on their defense skill than their constitution stat. The defense
skill's main purpose as coded, aside from determining max hitpoints, is to
factor in to the calculation that determines if a physical attack against
the defender is successful - which makes sense. However, we found a while
back that a code error in that "attack success" calculation is causing the
game to treat every attack against a player as if the player has maxed the
defense skill. I think the conclusion at the time was to just leave the
error as it was, since it had been that way for a long time and seemed like
it could make the game disproportionately more difficult for lower level
players if it were fixed.

I don't remember how hit points were calculated before the current method,
or what prompted the change, but to me a reasonable way of handling HP gain
while decoupling it from the defense skill would be fixing the
aforementioned bug and implementing a system similar to what Aion described
- some like D&D where every class has a preassigned number of hit dice that
roll on level up to figure out how much to increase the character's max HP.

Then the character's constitution stat bonus could modify it from there
(using the current stat bonus range of -25% at 5 con to +25% at 205 con).
Could even be possible to make constitution a little more of a "dynamic"
stat in the sense that max HP could automatically adjust whenever a
character's con changes due to equipment bonuses or any spell affects
potentially added down the road (for example, something like a "Hero's
Might" Deikhan prayer that increases the recipient's constitution by some
amount for the duration of about one decently tough fight - maybe made
mutually exclusive with prayers that buff other tank stats such as agi or
brawn).

With these changes I think several things could be accomplished:

1) Con would become a more valuable stat for non-tank characters, as they
could actually benefit from it without being required to spend a ton of
time tanking (or tanking in short bursts just long enough to get a defense
hone over and over until they reach a reasonably safe HP level, as I've
done in the past on my chars and always hated).

2) Tank classes would actually be better tanks than non-tank classes of the
same level from much earlier on, as they wouldn't have to slowly raise
their defense skill to actually benefit from a higher con stat like they do
now. Currently, a warrior and a cleric of the same level with the same
amount of con/agi/brawn and similar AC are basically identical as far as
tanking ability up until the warrior gets some of their advanced
disciplines. In fact, in a lot of situations clerics are still potentially
better tanks than a warrior with advanced defense and defensive trance
because their buffs affect themselves much more strongly than they do other
players.

A cleric with self-cast sanc, armor, and bless could easily take less
damage than a warrior using defensive trance in the same fight, because the
fewer attacks that *do* get through trance will be doing much more damage
per hit to the warrior compared to the higher volume of lower damage hits
on the cleric. Additionally, defensive trance causes a warrior to run out
of moves very quickly without constant refreshes/second winds and also
makes them unable to taunt or rescue without breaking the trance, which is
a huge disadvantage in a lot of situations. Then if you add in the fact
that mobs with moves like hurl are extremely likely to prioritize them
against a trancing warrior, it often makes warrior tanking a huge pain. I
guess that's kind of getting into an entirely separate issue, though.

If clerics had something like 50% less max HP on average compared to a
warrior or deikhan of the same level/stats it would do a lot, in my
opinion, to incentivize playing a warrior or deikhan over just using a
cleric with high tank stats to fill the role. I realize this would affect
solo or small group play a lot more than large groups, who already tend to
use a real tank, but those aren't nearly as common anymore.

3) Having a high defense skill would continue to be important, but for a
different and much more logical reason. Currently, raising your defense
skill is important to every character just to get to a bare minimum level
of HP where you won't instantly die if you get targeted by the wrong mob.

After these suggested changes, almost every character would reach that bare
minimum level of survivability just due to the HP gained from leveling
(unless you were something like an urban elf mage who decided to take -25
con at creation, in which case God help you).

If you had two characters with the same max HP but one had spent all their
time hitting (and therefore neglecting to raise their defense skill)
whereas the other had defense maxed, the latter would be getting hit far
less and presumably be much easier to keep alive. It would also make the
overall concept of the defense skill more logical - as in, it's a measure
of a character's ability to avoid being hit in combat and is improved by
being the target of attacks repeatedly.

4) This would also be a good opportunity to add functionality to the
defense skill. One of the things that always really annoyed me while
playing my warrior and tanking lots of high-level fights in a row was how
quickly my equipment would get beat up. I'd have to take breaks to go
repair after even a few fights if I got unlucky, or else risk eq scrapping
at inopportune times in the next fight. Making defense and/or advanced
defense learnedness reduce the rate of eq. damage would be a really awesome
change, in my mind, and it would make perfect sense thematically: A person
who had spent so much time being the target of attacks would be better at
"moving with the blows" to cause them to land at less damaging angles, etc.
Plus, eq. damage has always felt to me like one of those
"realistic-yet-ultimately-just-a-buzzkill" features that can bring the
game's quality of life down. There's nothing worse than being in a fun
group but having to keep stopping to let the tank repair their equipment
after every tough fight while everyone's spells run out and the zone repops
before you got to your primary target.

---------------

All that being said, these ideas are irrelevant without someone to actually
code them. I've been wishing for a while now that I could contribute to the
code but I don't have anywhere near the level of technical C++ expertise
that people like Elmo and Ryan do, so I haven't really seen anything I felt
capable of helping with. Stuff like this, however, seems like something I'd
be able to handle since it's more about altering/tweaking existing code and
thorough logic than finding and fixing low-level, technical problems (which
I find so much more impressive, but just am not good enough with C++ to do
yet). If the people in charge were to agree on what changes should be made
and gave the go-ahead I'd be happy to devote some time to working on
implementing them.


On Jan 21, 2018 8:01 PM, "Aion" <notifications@github.com> wrote:

This is a change I'd like to see rolled back or heavily modified. I can see
the thinking behind why HP was directly linked to defense hones at one
point, but I don't feel it's the right move. This game is not about who
tanks the most, as most classes don't tank.

I think we need traditional D&D style leveling where you gain a dice worth
of HP upon gaining a level.

A more complex solution: Perhaps the Defense skill could grant some
percentage of the HP total. Maybe 25% of a characters total HP comes from
Defense hones. Certainly not all of it. It makes more sense this way to me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sneezymud/sneezymud/issues/129>, or mute the thread

**Comment by cizra** [comment] 2018-01-23 07:17
Responding only to the coding part:
Any code you cook up, I'll review and help fix & finalize. You can also ask for help finding things, etc.

**Comment by Aion2501** [comment] 2018-01-23 13:14
Once upon a time, the defense skill factored into whether or not someone else could successfully hit you.

`Level, AC, and Defense skill are the primary base factors in your ability to evade hits in combat.`

I'd like to see it go back to that. Perhaps simply adding an internal scaling AC bonus tied to Defense. Skills go from 1-100. An idea: The first 50 points give you a penalty of 2AC (because you suck at taking hits) and the next 50 points start replacing that negative with a positive -4AC until finally at 100max you have a worthy scrapper who has an extra 100 AC. 

Regarding HP, there are already mechanics in place to make certain classes more meaty. Warriors, Deikhans, and (Monks?_?) get the Advanced Defense skill option.  Going back to a flat return of HP per level + CON modifier AFTER total is a simple solution. 

We can always go back to the drawing board later with part of your HP pool depending on defense or having more/less HP dice for each class, etc.

**Comment by drewhershey** [comment] 2018-01-23 17:00
Thanks Cizra, I'll most likely be taking you up on that offer.

After looking through the code, which I probably should have done before writing my original ridiculously long post, it looks like every class already gains a set number of HP per level: 

**Class: HP Per Level / HP Range @ Lvl 50 Based on Con**
Mage: 7.5 / 239 - 373
Cleric: 8 / 253 - 396
Warrior: 8.5 / 369 - 577 (with adv. defense)
Thief: 8 / 253 - 396
Shaman: 7.5 / 239 - 373
Deikhan: 7.5 / 329 - 515 (with adv. defense)
Monk: 5.5 / 183 - 286 (no adv. defense) / 249 - 390 (with adv. defense)

I assume there was some reasoning behind those numbers when they were set originally, although I have no idea what it was. Not sure how it makes sense for mages and shaman to get the same HP per level as a deikhan, for instance, or why a cleric or thief would get more than a deikhan.

A character's defense and advanced defense skills are represented as a value from 0 - 100, with 0 being completely untrained and 100 being maxed.

Currently, the formula to calculate a character's max HP is: 
`[Base HP + Age HP Mod + (Class HP Per Level * (.35 * Defense Skill Value + .15 * Adv. Defense Skill Value))] * Constitution Modifier + HP Bonuses from Spells/Equipment`

- Base HP is hard coded to 21. 
- Age HP Mod is hard coded to 16 unless you select the "realistic aging" character trait during creation. 
- The constitution modifier ranges from -20% HP at 5 Con to +25% HP at 205 Con, and dynamically takes bonuses to Con from gear into account. 
- This is the _only_ place in the code that I can find where the advanced defense skill has any impact whatsoever. It appears this skill was added purely to give warriors, deikhans, and monks (why? because of their abnormally low HP/level?) the option to get what amounts to 15 more levels worth of HP over other classes.

What this all means is that up through level 35, a character's max HP will generally be in line with their level multiplied by their class HP mod _**if**_ they tank often enough to keep their defense skill as high as it can possibly be. If they never raise their defense skill they could literally have the HP of a level 1 character at level 50. After they max the defense skill their HP will "remain" at level 35 unless they're eligible for and train Advanced Defense.

Personally, I don't think this system makes a whole lot of sense and feel it forces a playstyle I don't really enjoy. 

If I had to guess, I would say it was designed this way to discourage power leveling by making a character extremely fragile if they leveled up mostly via killing cudgeled or super gimped mobs. I'm not sure the remaining players and admins care nearly as much about power leveling as people did back in the day.

In my experience all this system really accomplishes is making leveling as a group more frustrating because you have to worry about getting everyone some turns tanking so they don't stay too squishy, instead of just allowing people to play the roles they want.

At this point my initial idea for how to fix it would be:

1. Rework the advanced defense skill to give it entirely new functionality related to tanking, and probably remove it from the monk class. Possible options off the top of my head: Flat % damage reduction; Reduce equipment damage rate; Increase rate of parry/dodge; Magic resistance. Perhaps the new functionality could scale with defensive stats somehow. 

Or we could just remove/disable the skill entirely, refund any practices that were used towards it, and consider a separate project in the future to tweak it.

2. Change the formula for max HP to be simply `Base HP + Age HP Mod + (Class HP Per Level * Character Level) * Constitution Modifier + HP Bonus from Spells/Equipment`. Any level 50 characters without advanced defense would see an increase in HP equal to 15 levels worth. Level 50 characters that have advanced defense maxed would see no change.

3. Adjust the class HP bonus per level numbers to make them more logical and promote using the tank classes as tanks over classes like clerics that already provide much more utility.

4. Fix the error in the application of the defense skill at line 2651 of combat.cc: 
        `amt *= max(100, (int) getSkillValue(SKILL_DEFENSE));`
becomes
        `amt *= max(10, (int) getSkillValue(SKILL_DEFENSE));`

This would revert an error in the code to bring the defense skill back to its intended functionality. The original devs wanted it to have a floor of 10 (to give lowbies some basic protection I assume), with a max of 100 based on the defense skill. Instead, for who knows how long, it's been returning a flat 100 no matter what the character's defense skill is, effectively treating all characters as if they've maxed defense.

This would cause characters to suddenly start getting hit more often if they didn't have the defense skill trained up. On the other hand, it would make people who **do** often tank, and therefore have a higher defense skill, better at avoiding attacks than those who don't. If after testing it was felt that this made low level combat too difficult things could be tweaked. Hopefully the increase in HP at those same levels would help offset.

If we can get some consensus on what should be done I think I could make the changes pretty quickly.

**Comment by Aion2501** [comment] 2018-01-25 04:06
I can explain SOME of this. First of all, a lot of the game was just coded by whoever felt they had a good idea. Not all of it is well thought out. Some of it is good in theory, but not in practice.

That said, warriors are essentially HP/skill tanks. Deikhans are AC/spell tanks. They get that +25% AC bonus for being mounted. Someone probably thought the balance was to give them less HP. 

This of course was also coded before the global level increase and defense/hp change. With higher level mobs and mount problems, Deikhans sort of fell into disuse. (See my mounts/deikhan ticket)
You'd have to ask Travis, but my guess with monks is that it made sense to him that martial artists would learn defensive skills differently than other classes and he went with the low HP/advanced defense combo. 

Short-term: Lets get a quick fix to put HP back to level based instead of defense skill based.
Long-term: Overhaul defense skill.

**Comment by wershlak** [comment] 2021-08-07 07:57
This is resolved

**Closed by wershlak** 2021-08-07 07:57 UTC
Labels: balance
